### ISSUE TITLE
Muito bom  o material

### ISSUE THREAD

**Issue by DevJoseWeb** [MicrosoftDocs/azure-docs.pt-br#102]
Muito bom  o material

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 12620b1a-c104-d0d4-cd73-307d232beea8
* Version Independent ID: dcad1638-a9d2-91e2-f3f4-f43cc6c09a9f
* Content: [Uma solução preditiva para o risco de crédito com o Machine Learning](https://docs.microsoft.com/pt-br/azure/machine-learning/studio/walkthrough-develop-predictive-solution)
* Content Source: [articles/machine-learning/studio/walkthrough-develop-predictive-solution.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/machine-learning/studio/walkthrough-develop-predictive-solution.md)
* Service: **machine-learning**
* GitHub Login: @heatherbshapiro
* Microsoft Alias: **hshapiro**

**Comment by LisandroSu** [comment]
Olá, @DevJoseWeb , 

Seus comentários são muito bem-vindos. Ficamos felizes em ver que sua experiência com nossa documentação atende às suas expectativas. 

Incentivamos você a fornecer seus comentários valiosos para que possamos continuar melhorando sua experiência. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
