### ISSUE TITLE
Is there any preview to allow PaaS services?

### ISSUE THREAD

**Issue by matheus-santoro** [MicrosoftDocs/azure-docs.pt-br#103]
Is there any chance that PaaS services such as SQL databases to be in the list of exceptions?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2632af75-7664-b79b-ac5b-c7c17e6a609a
* Version Independent ID: 6ecf71b6-77c4-3ab6-8ec9-353ea407d70f
* Content: [Configurar Redes Virtuais e firewalls do Armazenamento do Microsoft Azure](https://docs.microsoft.com/pt-br/azure/storage/common/storage-network-security#exceptions)
* Content Source: [articles/storage/common/storage-network-security.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/storage/common/storage-network-security.md)
* Service: **storage**
* GitHub Login: @cbrooksmsft
* Microsoft Alias: **cbrooks**

**Comment by LisandroSu** [comment]
Hello, @matheus-santoro  
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
