### ISSUE TITLE
Repositório Samples

### ISSUE THREAD

**Issue by rudrigodefreitasoliveira** [MicrosoftDocs/azure-docs.pt-br#105]
Olá amigo, como vai?
A pasta dos scritps não está no github

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: edb1fa6c-8433-882f-8b97-4d381f885b1d
* Version Independent ID: aad3ec71-363f-3500-8bcd-dc040f71821e
* Content: [Início Rápido para aprender a usar o Serviço Azure SignalR](https://docs.microsoft.com/pt-br/azure/azure-signalr/signalr-quickstart-dotnet-core)
* Content Source: [articles/azure-signalr/signalr-quickstart-dotnet-core.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/azure-signalr/signalr-quickstart-dotnet-core.md)
* Service: **signalr**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #14068](https://github.com/MicrosoftDocs/azure-docs/issues/14068) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Olá, @rudrigodefreitasoliveira 

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original. 
Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/azure-docs/issues/14068 

Agradecemos sua contribuição aos nossos artigos. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
