### ISSUE TITLE
Old repo sitting in Azure GitHub org

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/azure-docs.pt-br#114]
This looks to be an old copy of this repo https://github.com/Azure/azure-content-ptbr
If it is, it would be good to remove it to prevent confusion.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #17362](https://github.com/MicrosoftDocs/azure-docs/issues/17362) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @nschonni: 

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/azure-docs/issues/17362. 
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
