### ISSUE TITLE
Reconhecer Texto

### ISSUE THREAD

**Issue by JoniBlade** [MicrosoftDocs/azure-docs.pt-br#115]
Boa Noite, Baixei o projeto e executei conforme as instruções acima, porem ele só analiza e nao identificar oque ele reconheceu,  se eu uso const string uriBase = "https://brazilsouth.api.cognitive.microsoft.com/vision/v2.0/recognizeText?mode=Printed"; ele me retorna o seguinte erro: Wait a moment for the results to appear.

Error reading JToken from JsonReader. Path '', line 0, position 0.

Press Enter to exit...
Alguem poderia ajudar?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 5fdd9884-2d15-e480-e057-dfb72d89f2fb
* Version Independent ID: 37f24981-566c-5d2d-87cc-4878e8699342
* Content: [Início Rápido: analisar uma imagem local – REST, C# – Pesquisa Visual Computacional - Azure Cognitive Services](https://docs.microsoft.com/pt-br/azure/cognitive-services/Computer-vision/QuickStarts/CSharp-analyze)
* Content Source: [articles/cognitive-services/Computer-vision/QuickStarts/CSharp-analyze.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/cognitive-services/Computer-vision/QuickStarts/CSharp-analyze.md)
* Service: **cognitive-services**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by LisandroSu** [comment]
Olá, @JoniBlade 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
