### ISSUE TITLE
Disable system-assigned identity from an Azure VM

### ISSUE THREAD

**Issue by marcelotpcosta** [MicrosoftDocs/azure-docs.pt-br#116]
I tried to turnoff it on portal and CLI (az vm update -n myVM -g myResourceGroup --set identity.type="none") , but I still can't resize my VM with error associated to managed identity.
"Failed to resize virtual machine 'VM' to size 'Size'. Error: The principalId 'aaa' on the resource's Identity property must be null or empty for 'SystemAssigned' identity type."

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a6086b67-2bce-b72f-f541-2723e24ac68a
* Version Independent ID: 0796f937-9c9d-d818-a27b-3ef4feab5497
* Content: [Como configurar identidades gerenciadas atribuídas ao usuário e ao sistema em uma VM do Azure usando a CLI do Azure](https://docs.microsoft.com/pt-br/azure/active-directory/managed-identities-azure-resources/qs-configure-cli-windows-vm)
* Content Source: [articles/active-directory/managed-identities-azure-resources/qs-configure-cli-windows-vm.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/active-directory/managed-identities-azure-resources/qs-configure-cli-windows-vm.md)
* Service: **active-directory**
* GitHub Login: @daveba
* Microsoft Alias: **daveba**

**Comment by LisandroSu** [comment]
Olá, @marcelotpcosta 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
