### ISSUE TITLE
Erro de tradução

### ISSUE THREAD

**Issue by imbroisi** [MicrosoftDocs/azure-docs.pt-br#196]
Há um erro na tradução em "Pré-Requisitos". No trecho "Acesso ao GitHub ou repositório Git externo que contém o .NET, Java, PHP, nó, Python ou código da Web estático.", a tradução do original "Node", ficou como "nó". O correto é "Node" mesmo.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 679c851f-0cc9-3b99-1d31-88672aebb693
* Version Independent ID: 91ce6957-0bc6-1934-8ac9-f7af096caa95
* Content: [Tutorial: Criar um pipeline de CI/CD para o seu código existente usando o Azure DevOps Projects](https://docs.microsoft.com/pt-br/azure/devops-project/azure-devops-project-github)
* Content Source: [articles/devops-project/azure-devops-project-github.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/devops-project/azure-devops-project-github.md)
* Product: **devops**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by CeciAc** [comment]
Olá, @imbroisi 

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/azure/devops-project/azure-devops-project-github.  

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
