### ISSUE TITLE
Erro ortografia

### ISSUE THREAD

**Issue by MarcoAntonioMada** [MicrosoftDocs/azure-docs.pt-br#198]
Na linha da frase abaixo, o correto é: 
Uma política do Azure consiste nos seguintes componentes:
**Uma** diretiva é uma regra

Faltou a letra a na palavra Uma.

Incorreto:
Uma política do Azure consiste nos seguintes componentes:
**Um** diretiva é uma regra

**Comment by CeciAc** [comment]
Olá, @MarcoAntonioMada,
Estamos acompanhando nosso comentário anterior. Precisamos de mais informações para podermos endereçar seus comentários. Você poderia fornecer informações mais detalhadas e explicar seu comentário?
Atenciosamente,
Equipe Internacional do Microsoft DOCS

**Comment by MarcoAntonioMada** [comment]
Boa noite,

A sugestão é referente ao erro de ortografica em uma frase especifica do https://docs.microsoft.com/pt-br/azure/security-center/tutorial-security-policy.



Uma política do Azure consiste nos seguintes componentes:

  *   Um diretiva é uma regra.

O correto é:



Uma diretiva é uma regra.
[https://docs.microsoft.com/_themes/docs.theme/master/en-us/_themes/images/microsoft-header.png]<https://docs.microsoft.com/pt-br/azure/security-center/tutorial-security-policy>

Tutorial da Central de Segurança do Azure - Definir e avaliar as políticas de segurança | Microsoft Docs<https://docs.microsoft.com/pt-br/azure/security-center/tutorial-security-policy>
A Central de Segurança ajuda a garantir a conformidade com os requisitos de segurança regulatórios ou corporativos usando-se políticas de segurança para definir a configuração desejada das cargas de trabalho.Security Center helps ensure compliance with company or regulatory security ...
docs.microsoft.com


Obrigado.



Marco Antonio (Mada)
MCSA Office 365
MCSE Productivity
Linkedin: https://www.linkedin.com/in/marcoantoniomada
Twitter: https://twitter.com/MarcoASilvaBR
www.windowsbrasil.com.br

________________________________
De: Cecilia Acevedo <notifications@github.com>
Enviado: segunda-feira, 21 de janeiro de 2019 18:35
Para: MicrosoftDocs/azure-docs.pt-br
Cc: MarcoAntonioMada; Mention
Assunto: Re: [MicrosoftDocs/azure-docs.pt-br] Erro ortografia (#198)


Olá, @MarcoAntonioMada<https://github.com/MarcoAntonioMada>,
Estamos acompanhando nosso comentário anterior. Precisamos de mais informações para podermos endereçar seus comentários. Você poderia fornecer informações mais detalhadas e explicar seu comentário?
Atenciosamente,
Equipe Internacional do Microsoft DOCS

**Comment by v-maudel** [comment]
Olá, @MarcoAntonioMada ,  

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/azure/security-center/tutorial-security-policy#how-security-policies-work.  

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by MarcoAntonioMada** [comment]
Obrigado.




Marco Antonio (Mada)
MCSA Office 365
MCSE Productivity
Linkedin: https://www.linkedin.com/in/marcoantoniomada
Twitter: https://twitter.com/MarcoASilvaBR
www.windowsbrasil.com.br

________________________________
De: Mauricio de los Santos <notifications@github.com>
Enviado: sexta-feira, 8 de fevereiro de 2019 17:38
Para: MicrosoftDocs/azure-docs.pt-br
Cc: MarcoAntonioMada; Mention
Assunto: Re: [MicrosoftDocs/azure-docs.pt-br] Erro ortografia (#198)


Olá, @MarcoAntonioMada<https://github.com/MarcoAntonioMada> ,

Agradecemos seus comentários.

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/azure/security-center/tutorial-security-policy#how-security-policies-work.  <https://docs.microsoft.com/pt-br/azure/security-center/tutorial-security-policy#how-security-policies-work.%C2%A0%C2%A0>

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários.

Atenciosamente,
Equipe Internacional do Microsoft DOCS
