### ISSUE TITLE
Exit with code=255

### ISSUE THREAD

**Issue by danielfs1987** [MicrosoftDocs/azure-docs.pt-br#211]
Didi all steps as required but at the end we got the error below:

Starting] Upload sketch - app.ino
[Warning] Output path is not specified. Unable to reuse previously compiled files. Upload could be slow. See README.
Carregando configura��o...
Inicializando pacotes...
Preparando placas...
java.lang.NullPointerException
	at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:679)
	at processing.app.Base.onBoardOrPortChange(Base.java:1313)
	at processing.app.Base.&lt;init&gt;(Base.java:276)
	at processing.app.Base.main(Base.java:145)
[Error] Exit with code=255

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 6908b99a-b62b-0596-3dbe-c2fec0260b2b
* Version Independent ID: f34e44f2-3d3d-cbcd-d626-7c9b4115a0b1
* Content: [ESP8266 para a nuvem - Conectar o Feather HUZZAH ESP8266 ao Hub IoT do Azure](https://docs.microsoft.com/pt-br/azure/iot-hub/iot-hub-arduino-huzzah-esp8266-get-started)
* Content Source: [articles/iot-hub/iot-hub-arduino-huzzah-esp8266-get-started.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/iot-hub/iot-hub-arduino-huzzah-esp8266-get-started.md)
* Service: **iot-hub**
* GitHub Login: @rangv
* Microsoft Alias: **rangv**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #23929](https://github.com/MicrosoftDocs/azure-docs/issues/23929) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @danielfs1987 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/23929.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
