### ISSUE TITLE
Erro Erro

### ISSUE THREAD

**Issue by gabrielluizbh** [MicrosoftDocs/azure-docs.pt-br#213]
Já tente diversas vezes instalar no Windows Server 2019 e nada, só acontece erro.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 76dad6d5-9991-e15e-0283-1d8d49c35df4
* Version Independent ID: baa58543-1be8-aa7c-15b9-db35f071f4fb
* Content: [Usar o Servidor de Backup do Azure para fazer backup de cargas de trabalho no Azure](https://docs.microsoft.com/pt-br/azure/backup/backup-azure-microsoft-azure-backup)
* Content Source: [articles/backup/backup-azure-microsoft-azure-backup.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/backup/backup-azure-microsoft-azure-backup.md)
* Service: **backup**
* GitHub Login: @pvrk
* Microsoft Alias: **adigan**

**Comment by LisandroSu** [comment]
Olá, @gabrielluizbh 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
