### ISSUE TITLE
Azure Cognitive/Computer Vision/OCR - Quantidade diferente de "textos" encontrados nas mesmas imagens

### ISSUE THREAD

**Issue by acturcato** [MicrosoftDocs/azure-docs.pt-br#214]
Olá a todos!

Implementei código do "tutorial": Início Rápido: Extrair texto impresso (OCR) – REST, C# - Azure Cognitive Services.

Tudo está funcionando corretamente, exceto que, a quantidade total de "textos" encontrados nas imagens que testei rodando o código em C# **difere da quantidade** de "textos" encontrados com as mesmas imagens quando utilizo a versão web DEMO (https://azure.microsoft.com/id-id/services/cognitive-services/computer-vision/) seção "Read text in images".

A versão web DEMO consegue encontrar uma maior quantidade de textos nas imagens.
**Por que isso ocorre?**

link de duas imagens que utilizei nos testes:
link 1:
http://autos.culturamix.com/blog/wp-content/gallery/verificar-a-procedencia-do-carro-pela-placa-2/Verificar-a-Procedencia-Do-Carro-Pela-Placa-3.jpg

link 2:
http://s2.glbimg.com/IAA89fWI426EK2aGsGhGIr4JmFI=/620x465/top/s.glbimg.com/jo/g1/f/original/2015/07/23/veiculo_clonado_localizado_na_quadra_106_norte_1.jpg

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 9d6a5f5a-4f15-366c-891a-5c953b4a4643
* Version Independent ID: 3090f05f-8557-3296-fda3-3cd28920556b
* Content: [Início Rápido: Extrair texto impresso (OCR) – REST, C# - Azure Cognitive Services](https://docs.microsoft.com/pt-br/azure/cognitive-services/computer-vision/quickstarts/csharp-print-text)
* Content Source: [articles/cognitive-services/Computer-vision/QuickStarts/CSharp-print-text.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/cognitive-services/Computer-vision/QuickStarts/CSharp-print-text.md)
* Service: **cognitive-services**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by CeciAc** [comment]
Olá, @acturcato 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
