### ISSUE TITLE
O serviço não é agnóstico ?

### ISSUE THREAD

**Issue by edulemasson** [MicrosoftDocs/azure-docs.pt-br#215]
Gostaria de personalizar outras decisões além de só conteúdo web. Também é importante para o meu negócio poder programar a função de recompensa e enviar para o decision service via API para que ele aprenda com meus próprios critérios de sucesso.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e8524a82-8447-cd84-6d7c-86c443a68bb0
* Version Independent ID: 16d57404-f1df-5863-f1c5-bd358a42b372
* Content: [O que é o Serviço de Decisão Personalizada?](https://docs.microsoft.com/pt-br/azure/cognitive-services/custom-decision-service/custom-decision-service-overview)
* Content Source: [articles/cognitive-services/custom-decision-service/custom-decision-service-overview.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/cognitive-services/custom-decision-service/custom-decision-service-overview.md)
* Service: **cognitive-services**
* GitHub Login: @alekh
* Microsoft Alias: **slivkins**

**Comment by CeciAc** [comment]
Olá, @edulemasson 

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
