### ISSUE TITLE
Internal LoadBalancer Pricing

### ISSUE THREAD

**Issue by matheus-santoro** [MicrosoftDocs/azure-docs.pt-br#216]
Hello

https://azure.microsoft.com/en-us/pricing/details/load-balancer/ says that "Load balancing between Virtual Machines that reside inside of a Virtual Network (Internal Load Balancing) is free of charge." 
The Azure calculator, though  does not specify these options, only the SKU.

Does this mean that an internal Load Balancer, even on Standard SKU will be free of charge?

Thank you!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 09325ff2-5a0a-0aff-e3cb-d1c0585a6842
* Version Independent ID: f370d680-5d1d-99a9-e350-7d9551d24ce6
* Content: [O que é o Azure Standard Load Balancer?](https://docs.microsoft.com/pt-br/azure/load-balancer/load-balancer-standard-overview#pricing)
* Content Source: [articles/load-balancer/load-balancer-standard-overview.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/load-balancer/load-balancer-standard-overview.md)
* Service: **load-balancer**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by CeciAc** [comment]
Hello, @

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback/Comentários sobre o produto" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by matheus-santoro** [comment]
Hello @CeciAc thanks for your reply.

My issue is about the documentation, since it does not state clear whether the resource is free or not. One link says is free of charge and another says Standard LB has a charge.

I would like clarification on this point, please.

**Comment by matheus-santoro** [comment]
My point is precisely about the documentation, it is not clear whether it is free or not to create an internal Load Balancer.
The documentation misleads us into two different points.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25941](https://github.com/MicrosoftDocs/azure-docs/issues/25941) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello @matheus-santoro 
I moved this issue to the en-us repo so they can evaluate your suggestion
https://github.com/MicrosoftDocs/azure-docs/issues/25941

Kind regards,
Microsoft DOCS International Team
