### ISSUE TITLE
Class ServiceClient not found

### ISSUE THREAD

**Issue by RePinheiro** [MicrosoftDocs/azure-docs.pt-br#220]
After installing Nuget I located the DeciveClient class, but I did not find the ServiceClient class

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ba79df4d-c64b-7950-3ae9-6f28ea94409b
* Version Independent ID: 7ad0c568-0df2-3be8-f221-0fb846bf575c
* Content: [Mensagens da nuvem para o dispositivo com o Hub IoT do Azure (.NET)](https://docs.microsoft.com/pt-br/azure/iot-hub/iot-hub-csharp-csharp-c2d)
* Content Source: [articles/iot-hub/iot-hub-csharp-csharp-c2d.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/iot-hub/iot-hub-csharp-csharp-c2d.md)
* Service: **iot-hub**
* GitHub Login: @robinsh
* Microsoft Alias: **robin.shahan**

**Comment by CeciAc** [comment]
Hello, @RePinheiro 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by robinsh** [comment]
@ceciac Please reopen this, and I'll take a look at it. This could be a problem with the code in the article. 

@RePinheiro Can you tell exactly what step you were at when the serviceClient wasn't found? Did you copy those two lines of code (static ServiceClient… and static string connectionString…) into the Program class in Program.cs? When you do that, then the Task SendCloudToDeviceMessageAsync finds it and uses it, and should work fine. 
Or do you mean when you pasted in those two lines of static variables, it doesn't find the ServiceClient class? Can you be sure you are using the most recent NuGet package for Microsoft.Azure.Devices?

**Comment by robinsh** [comment]
@RePinheiro Take a look at my post, and let me know if it helps.

**Comment by RePinheiro** [comment]
Hello, I'm sorry for the delay, I managed to solve it, after trying to clean the solution and compile I reinstalled visual studio, after installation the package started working normally!

**Comment by robinsh** [comment]
@RePinheiro No worries. Thanks for coming back and checking it out again. Glad it's working now. 

#please-close
