### ISSUE TITLE
Environment Variable.

### ISSUE THREAD

**Issue by sique976** [MicrosoftDocs/azure-docs.pt-br#230]
I did not understand this step. Humm don´t know which part or where to put it.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 893ea9b1-d405-555b-7a65-f5647a85f752
* Version Independent ID: e56e12dd-8168-915f-ff76-e9799f7bca64
* Content: [Criar aplicativo Node.js com MongoDB – Serviço de Aplicativo do Azure](https://docs.microsoft.com/pt-br/azure/app-service/app-service-web-tutorial-nodejs-mongodb-app#configure-an-environment-variable)
* Content Source: [articles/app-service/app-service-web-tutorial-nodejs-mongodb-app.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/app-service/app-service-web-tutorial-nodejs-mongodb-app.md)
* Service: **app-service-web**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by CeciAc** [comment]
Hello, @sique976 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
