### ISSUE TITLE
How to create custom Types for Named Entity Recognition

### ISSUE THREAD

**Issue by murilotn** [MicrosoftDocs/azure-docs.pt-br#239]
This functionality would be very useful, by the fact you need to understand the semantic value of each entity in your text. Semantic here is your local meaning, what really this word means for you, a kind of relationship with your context.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: fe556b84-8429-ced1-e5fb-f9f567e72b3b
* Version Independent ID: 2e40c5db-f3ca-b816-3f17-60492bd11606
* Content: [Usar o reconhecimento de entidade com a API de Análise de Texto - Azure Cognitive Services](https://docs.microsoft.com/pt-br/azure/cognitive-services/text-analytics/how-tos/text-analytics-how-to-entity-linking#feedback)
* Content Source: [articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-entity-linking.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/cognitive-services/text-analytics/how-tos/text-analytics-how-to-entity-linking.md)
* Service: **cognitive-services**
* Sub-service: **text-analytics**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by CeciAc** [comment]
Hello, @murilotn 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
