### ISSUE TITLE
revisão do texto

### ISSUE THREAD

**Issue by thdotnet** [MicrosoftDocs/azure-docs.pt-br#26]
Ola, na página: https://docs.microsoft.com/pt-br/azure/azure-functions/functions-overview temos a seguinte frase:

"Funções podem tornar o desenvolvimento ainda mais produtivo e você pode usar a linguagem de desenvolvimento de sua escolha, por exemplo, C#, F#, Node.js, Python ou PHP." 

No entanto, logo após na sub seção de recursos temos mais linguagens.

"Opção de linguagem – escreva funções usando C#, F#, Node.js, Python, PHP, batch, bash ou qualquer executável." 

Minha sugestão é para que no primeiro parágrafo seja feita uma referência para a seção "Recursos", desta maneira, não haverá repetição de todas as linguagens em ambos os trechos.

**Comment by SunnyDeng** [comment]
@thdotnet , thank you for the contribution. the PR was merged at 6/5. Please reactivate if you see repro.
