### ISSUE TITLE
Activity lookup execution is succeeded when Stored Procedure throws an error

### ISSUE THREAD

**Issue by brtmeyer** [MicrosoftDocs/azure-docs.pt-br#415]
When using Lookup activity to execute an Azure SQL Stored Procedure, the activity is always succeeded, even when occurs an error in the execution of the Stored Procedure.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: ede89f3f-055a-b123-c081-8622a9035171
* Version Independent ID: c4fe312f-71a6-fe9b-e301-6e69c14ca46d
* Content: [Atividade de pesquisa no Azure Data Factory](https://docs.microsoft.com/pt-br/azure/data-factory/control-flow-lookup-activity)
* Content Source: [articles/data-factory/control-flow-lookup-activity.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/data-factory/control-flow-lookup-activity.md)
* Service: **data-factory**
* GitHub Login: @sharonlo101
* Microsoft Alias: **shlo**

**Comment by CeciAc** [comment]
Hello, @brtmeyer

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
