### ISSUE TITLE
Error "The response assertion is missing a required attribute"

### ISSUE THREAD

**Issue by souzasilvio** [MicrosoftDocs/azure-docs.pt-br#434]
After made the steps here described I am getting the message erro "The response assertion is missing a required atribute" to login in docusign with a test account.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 40756c7c-63eb-10f8-c8c4-17b57877bb7f
* Version Independent ID: 9de82050-9230-0236-c246-b2fd273888ce
* Content: [Tutorial: integração do Azure Active Directory com o DocuSign](https://docs.microsoft.com/pt-br/azure/active-directory/saas-apps/docusign-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/docusign-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/active-directory/saas-apps/docusign-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by CeciAc** [comment]
Hello, @souzasilvio 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by jeevansd** [comment]
@souzasilvio Make sure that the claims you have configured in Docusign you are sending them from Azure AD.
