### ISSUE TITLE
Exemplo que não funciona

### ISSUE THREAD

**Issue by GolfettoGuilherme** [MicrosoftDocs/azure-docs.pt-br#455]
Tentei implementar o exemplo de analise de sentimento mas sem sucesso. me é retornado esse erro: System.ArrayTypeMismatchException : Tentativa de acesso a um elemento como um tipo incompatível com a matriz.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 8f57e416-a37f-e719-4a3e-58a4e6390818
* Version Independent ID: dbb3821b-5793-b41b-9601-559b00e4096a
* Content: [Início Rápido: Chamar o serviço de Análise de Texto usando o SDK do Azure para .NET e C# - Azure Cognitive Services](https://docs.microsoft.com/pt-br/azure/cognitive-services/text-analytics/quickstarts/csharp#feedback)
* Content Source: [articles/cognitive-services/text-analytics/quickstarts/csharp.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/cognitive-services/text-analytics/quickstarts/csharp.md)
* Service: **cognitive-services**
* Sub-service: **text-analytics**
* GitHub Login: @raymondl
* Microsoft Alias: **assafi**

**Comment by srvbpigh** [comment]
Hello, @GolfettoGuilherme
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @GolfettoGuilherme

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
