### ISSUE TITLE
Dependency injection in this example

### ISSUE THREAD

**Issue by RicardoGaefke** [MicrosoftDocs/azure-docs.pt-br#469]
Hi,

This example worked fine for me, but I would like to use DI to inject configuration stuff such as connection strings. In the web project I use the classes' constructor for DI just like this way:

private readonly IOptions&lt;Secrets.ConnectionStrings&gt; _connectionStrings;

public MyEmail(IOptions&lt;Secrets.ConnectionStrings&gt; ConnectionStrings)
    {
      _connectionStrings = ConnectionStrings;
    }

But in this example I inserted a Console.WriteLine("constructor") and my constructor is not being fired. Can anybody please help me?

Thanks a lot.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 2e9e1a8a-6284-a230-061e-7cb27258571a
* Version Independent ID: 43390e30-04d6-6d4e-018e-21419dbb11e8
* Content: [Introdução ao WebJobs SDK - Azure](https://docs.microsoft.com/pt-br/azure/app-service/webjobs-sdk-get-started#feedback)
* Content Source: [articles/app-service/webjobs-sdk-get-started.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/app-service/webjobs-sdk-get-started.md)
* Service: **app-service-web**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by CeciAc** [comment]
Hello, @RicardoGaefke

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
