### ISSUE TITLE
Atualizar versões do SO suportadas

### ISSUE THREAD

**Issue by edu1409** [MicrosoftDocs/azure-docs.pt-br#470]
De acordo com o blog do time do Azure Service Fabric, o Windows Server 2019 já é suportado:
https://blogs.msdn.microsoft.com/azureservicefabric/2019/04/08/azure-service-fabric-6-4-refresh-release-5/

Obs: a página em inglês já está atualizada

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: c3a68b32-7ba0-74a4-510f-87a66dc05015
* Version Independent ID: f3b1165c-d6cf-ab4c-5b0c-ffe0c49434a6
* Content: [Preparação para implantação de cluster autônomo do Azure Service Fabric](https://docs.microsoft.com/pt-br/azure/service-fabric/service-fabric-cluster-standalone-deployment-preparation#feedback)
* Content Source: [articles/service-fabric/service-fabric-cluster-standalone-deployment-preparation.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/service-fabric/service-fabric-cluster-standalone-deployment-preparation.md)
* Service: **service-fabric**
* GitHub Login: @dkkapur
* Microsoft Alias: **dekapur**

**Comment by srvbpigh** [comment]
Hello, @edu1409
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @edu1409
Agradecemos seus comentários e sua sugestão.  
No momento, o arquivo está em processo de localização. O artigo será publicado em breve.
Agradecemos seu apoio. 

Atenciosamente,
Equipe do DOCS Global Experience da Microsoft
