### ISSUE TITLE
Créditos negativos

### ISSUE THREAD

**Issue by alancdias7** [MicrosoftDocs/azure-docs.pt-br#502]
O que ocorre se os créditos ficarem negativos? 
Exemplo: Minha aplicação está consumindo acima da linha de base, porém meus créditos acabaram, qual a ação realizada? O consumo do processamento volta para a linha de base ou continua acima, cobrando um valor excedente?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: f435b3d1-2e0b-378c-ce89-97defa822eff
* Version Independent ID: 32c3ea31-ae89-5a61-f99e-368bd7d72abc
* Content: [Tamanhos da série B de VM Windows do Azure](https://docs.microsoft.com/pt-br/azure/virtual-machines/windows/b-series-burstable#feedback)
* Content Source: [articles/virtual-machines/windows/b-series-burstable.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/virtual-machines/windows/b-series-burstable.md)
* Service: **virtual-machines-windows**
* GitHub Login: @ayshakeen
* Microsoft Alias: **ayshak**

**Comment by srvbpigh** [comment]
Hello, @alancdias7
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @alancdias7

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
