### ISSUE TITLE
Erro na formação da frase

### ISSUE THREAD

**Issue by totalys** [MicrosoftDocs/azure-docs.pt-br#530]
Verificar o erro de formação da frase:
"O OATH é um padrão livre que especifica os códigos de OTP (senha única) são gerados." no tópico: Tokens OATH de hardware (versão prévia pública)

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b8f14188-98ec-5c94-f408-162ee1baa076
* Version Independent ID: 41ed4874-e1e6-56d3-4de4-39c024d1e06c
* Content: [Métodos de autenticação-Azure Active Directory](https://docs.microsoft.com/pt-br/azure/active-directory/authentication/concept-authentication-methods#feedback)
* Content Source: [articles/active-directory/authentication/concept-authentication-methods.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/active-directory/authentication/concept-authentication-methods.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @totalys
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @totalys 

Agradecemos seus comentários. 

Nossa equipe linguística analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/azure/active-directory/authentication/concept-authentication-methods#feedback

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
