### ISSUE TITLE
Consumer Logs from Event Hub with Azure Functions and Application Insights

### ISSUE THREAD

**Issue by EdiFirst** [MicrosoftDocs/azure-docs.pt-br#562]
I believe that could be a good example to explore the ingestion of logs with Event Hub and consume that with Azure Function ( Trigger Event Hub) and show it on Application Insights without to configure a 3rd tool. I implementing this but could help if had detailed documentation.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: d24f4a76-ebfe-2d29-fd4e-acbe58b14603
* Version Independent ID: 513488cc-328f-5ec0-fffb-a3bca9125baa
* Content: [Monitorar APIs com o Gerenciamento de API do Azure, Hubs de Eventos e Moesif](https://docs.microsoft.com/pt-br/azure/api-management/api-management-log-to-eventhub-sample#feedback)
* Content Source: [articles/api-management/api-management-log-to-eventhub-sample.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/api-management/api-management-log-to-eventhub-sample.md)
* Service: **api-management**
* GitHub Login: @darrelmiller
* Microsoft Alias: **apimpm**

**Comment by srvbpigh** [comment]
Hello, @EdiFirst
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @EdiFirst 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team
