### ISSUE TITLE
A analise de custo não esta disponível ainda

### ISSUE THREAD

**Issue by mtrangel89** [MicrosoftDocs/azure-docs.pt-br#564]
A analise de custo não esta disponível ainda, sabem dizer se esta sendo disponibilizado aos poucos para CSP?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 302575cd-86c8-5ddb-97c6-b406925cf0f4
* Version Independent ID: 84c2ceb5-e2f5-f8f6-e755-4cada678cb1c
* Content: [Introdução ao gerenciamento de custos do Azure para parceiros](https://docs.microsoft.com/pt-br/azure/cost-management/get-started-partners#partner-access-to-billing-scopes-in-cost-management)
* Content Source: [articles/cost-management/get-started-partners.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/cost-management/get-started-partners.md)
* Service: **cost-management**
* GitHub Login: @bandersmsft
* Microsoft Alias: **banders**

**Comment by srvbpigh** [comment]
Hello, @mtrangel89
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@ishasahni1 can you help me with this issue?

**Comment by ishasahni1** [comment]
@CeciAc I am sorry I am not quite clear with the ask, is this localization not being in sync with en-us? Or is it more on the feedback around having content for Cost Analysis information for CSP?

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #41129](https://github.com/MicrosoftDocs/azure-docs/issues/41129) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
@ishasahni1 is not a loc issue, I moved it to the en-us repo
