### ISSUE TITLE
Standard SKU type for public static IP is invalid

### ISSUE THREAD

**Issue by andrepatete** [MicrosoftDocs/azure-docs.pt-br#565]
When creating static IP, I had problems with the Standard type.
Error Message Suggests Creating Basic Type SKU

 Warning  CreateOrUpdateLoadBalancer  2m19s (x7 over 7m37s)  azure-cloud-provider  network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="PublicIPAndLBSkuDoNotMatch" Message="Basic sku load balancer /subscriptions/xxxxxxxxxx/resourceGroups/mc_xxxxxxxxxx_eastus2/providers/Microsoft.Network/loadBalancers/kubernetes cannot reference Standard sku publicIP /subscriptions/xxxxxxxxxx/resourceGroups/MC_xxxxxxxxxx_eastus2/providers/Microsoft.Network/publicIPAddresses/nginx-ingress-ip." Details=[]

It worked for me

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 12009c1f-282d-2632-fac0-64b09c432833
* Version Independent ID: 6052d3d4-d295-9340-b16d-4c200e34cd73
* Content: [Crie um controlador de entrada HTTP com um endereço IP estático no AKS (Serviço de Kubernetes do Azure)](https://docs.microsoft.com/pt-br/azure/aks/ingress-static-ip#feedback)
* Content Source: [articles/aks/ingress-static-ip.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/aks/ingress-static-ip.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @andrepatete
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @andrepatete

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/44148

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
