### ISSUE TITLE
Forbidden (403) when copying files with '[' and '(' characteres (S3-compatible storage provider)

### ISSUE THREAD

**Issue by andremarques023** [MicrosoftDocs/azure-docs.pt-br#573]
I'm getting the following exception whenever I try to copy files under buckets with '[', ']', '(' or ')' characters in the name:

{
    "errorCode": "2200",
    "message": "Failure happened on 'Sink' side. ErrorCode=UserErrorFailedS3FileReadOperation,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=The operation on file File v7. (State).pdf under directory bucket-1506601XYZ is failed due to exception. ,Source=Microsoft.DataTransfer.ClientLibrary.MultipartBinaryConnector,''Type=Amazon.S3.AmazonS3Exception,Message=Error making request with Error Code Forbidden and Http Status Code Forbidden. No further error information was returned by the service.,Source=AWSSDK.Core,''Type=Amazon.Runtime.Internal.HttpErrorResponseException,Message=The remote server returned an error: (403) Forbidden.,Source=AWSSDK.Core,''Type=System.Net.WebException,Message=The remote server returned an error: (403) Forbidden.,Source=System,'",
    "failureType": "UserError",
    "target": "Copy bucket-1506601XYZ",
    "details": []
}

File name: File v7. (State).pdf. 

We are copying from a S3-compatible storage provider.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 710d4797-888a-ee10-f3e8-67b990e2f893
* Version Independent ID: ecc41588-d311-36e0-7257-914dac216c17
* Content: [Copiar dados do Amazon S3 (Simple Storage Service)](https://docs.microsoft.com/pt-br/azure/data-factory/connector-amazon-simple-storage-service)
* Content Source: [articles/data-factory/connector-amazon-simple-storage-service.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/data-factory/connector-amazon-simple-storage-service.md)
* Service: **data-factory**
* GitHub Login: @linda33wj
* Microsoft Alias: **jingwang**

**Comment by srvbpigh** [comment]
Hello, @andremarques023
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #46904](https://github.com/MicrosoftDocs/azure-docs/issues/46904) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Olá, @andremarques023,   

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original.  

Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/azure-docs/issues/46904.  

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente,  
Equipe Internacional do Microsoft DOCS
