### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 0xc01** [MicrosoftDocs/azure-docs.pt-br#582]
{1&gt;{2&gt;Próximas etapas&lt;2}&lt;1}

está bugado essa parte.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: aa688416-61ed-5a02-eab0-4a39b6cdc533
* Version Independent ID: c4aded8c-ae13-f863-362d-cc77f72fa023
* Content: [Anexar um disco de dados gerenciado a uma VM do Windows – Azure](https://docs.microsoft.com/pt-br/azure/virtual-machines/windows/attach-managed-disk-portal#next-steps)
* Content Source: [articles/virtual-machines/windows/attach-managed-disk-portal.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/virtual-machines/windows/attach-managed-disk-portal.md)
* Service: **virtual-machines-windows**
* Sub-service: **disks**
* GitHub Login: @roygara
* Microsoft Alias: **rogarana**

**Comment by srvbpigh** [comment]
Hello, @0xc01
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Olá, @0xc01,   

Sua contribuição é muito bem-vinda. Seus comentários são relacionados à documentação original.  

Portanto, estamos migrando este problema para o repositório em inglês. Verifique o status do problema aqui – https://github.com/MicrosoftDocs/azure-docs/issues/50437.  

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente,  
Equipe Internacional do Microsoft DOCS
