### ISSUE TITLE
Sample Code Improvement

### ISSUE THREAD

**Issue by GeisaFaustino** [MicrosoftDocs/azure-docs.pt-br#596]
I would like to suggest the follow improvement on the sample code.

![image](https://user-images.githubusercontent.com/32823639/80504247-42874280-8949-11ea-857e-47b9ddf8f9de.png)

I followed the instruction, but I do not why the version installed was not the latest one. I spent some time trying to understand what was happing because when running the sample code, it insisted to show me version v12, when this was not the version installed on my machine. Therefore, I belive that is better to print the current package version instead of a hard coded message.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 15591874-317e-ce4c-0dff-20d06b625e40
* Version Independent ID: be7fed9a-343a-0ec7-a94d-02c354d1ae33
* Content: [Início Rápido: biblioteca do armazenamento de Blobs do Azure v12 – Python](https://docs.microsoft.com/pt-br/azure/storage/blobs/storage-quickstart-blobs-python#feedback)
* Content Source: [articles/storage/blobs/storage-quickstart-blobs-python.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/storage/blobs/storage-quickstart-blobs-python.md)
* Service: **storage**
* Sub-service: **blobs**
* GitHub Login: @mhopkins-msft
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Hi @GeisaFaustino,

This is a good idea. I've created a work item on our backlog to consider adding this code update.

Thank you for the feedback! 
 ~ *Mark*

#please-close

**Comment by srvbpigh** [comment]
Hello, @GeisaFaustino
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
