### ISSUE TITLE
Rate - Overtranslation

### ISSUE THREAD

**Issue by mayra-ak** [MicrosoftDocs/azure-docs.pt-br#598]
Em rate - Prosody os valores devem ser separados por ponto (.) e não vírgula (,).

rate	Indica a taxa de fala do texto. Você pode expressar rate como:
Um valor relativo, expresso como um número que atua como um multiplicador do padrão. Por exemplo, um valor de 1 resulta em nenhuma alteração na taxa. Um valor de 0.5 (0,5 assim está errado) resulta em uma metade da taxa. Um valor de 3 resulta em uma viagem da taxa.
Um valor constante:
x-lento
lento
média
rápido
x-rápido
default

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: aae85d9f-b4f4-fc4d-cb0f-0fc4a1d4e7c9
* Version Independent ID: dbd55a99-dbde-a3f3-47a5-ded8309e2748
* Content: [Linguagem de marcação de síntese de fala (SSML) – serviço de fala - Azure Cognitive Services](https://docs.microsoft.com/pt-br/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp#adjust-prosody)
* Content Source: [articles/cognitive-services/Speech-Service/speech-synthesis-markup.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/cognitive-services/Speech-Service/speech-synthesis-markup.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @trevorbye
* Microsoft Alias: **trbye**

**Comment by srvbpigh** [comment]
Hello, @mayra-ak
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Olá, @mayra-ak :

 Agradecemos sua contribuição.

No momento, contribuições sobre problemas de tradução com relação ao conteúdo traduzido automaticamente não estão sendo aceitas.
Valorizamos seus comentários e sugestões sobre o conteúdo produzido por tradução humana, usado para treinar os mecanismos de tradução automática. Assim, com o passar do tempo, suas contribuições vão aprimorar a qualidade das traduções humana e automática.
Os tópicos produzidos por tradução humana podem ser diferenciados dos tópicos traduzidos automaticamente pelo valor de metadados ms.translationtype "HT" (versus "MT" para tradução automática) no cabeçalho de cada arquivo de conteúdo.

Agradecemos seu apoio.

Equipe do DOCS Global Experience da Microsoft

@ishasahni1

**Comment by mayra-ak** [comment]
Boa noite!


Agradeço seu retorno mas insisto nesse assunto. Eu segui o passo a passo do
tópico e gastei uma hora debugando o erro até ler em inglês. No Brasil
usamos a vírgula como separador decimal e o rate do prosody só aceita ponto
como separador. Se alguém seguir as instruções da documentação vai se
separar com o mesmo problema.

rate Indica a taxa de fala do texto. Você pode expressar rate como:
Um valor relativo, expresso como um número que atua como um multiplicador
do padrão. Por exemplo, um valor de 1 resulta em nenhuma alteração na taxa.
Um valor de 0,5 resulta em uma metade da taxa. Um valor de 3 resulta em uma
viagem da taxa.
Um valor constante:
x-lento
lento
média
rápido
x-rápido
default


Att,

Em ter, 19 de mai de 2020 20:02, Ramiro Del Greco <notifications@github.com>
escreveu:
