### ISSUE TITLE
topi

### ISSUE THREAD

**Issue by MuriloPetruci** [MicrosoftDocs/azure-docs.pt-br#600]
topi

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e178cd44-55d5-23ab-d965-94c47ada47dc
* Version Independent ID: c0f2ba6b-9c90-8975-6796-009417be4ffa
* Content: [Criar um aplicativo Web do Python Flask usando a API para MongoDB do Azure Cosmos DB](https://docs.microsoft.com/pt-br/azure/cosmos-db/create-mongodb-flask#feedback)
* Content Source: [articles/cosmos-db/create-mongodb-flask.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/cosmos-db/create-mongodb-flask.md)
* Service: **cosmos-db**
* Sub-service: **cosmosdb-mongo**
* GitHub Login: @markjbrown
* Microsoft Alias: **mjbrown**

**Comment by srvbpigh** [comment]
Hello, @MuriloPetruci
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Olá, @MuriloPetruci , 

Realmente gostaríamos de receber seu comentário e vamos melhorar sua experiência no docs.microsoft.com. Porém precisamos de mais informações para podermos endereçar seus comentários. Você poderia fornecer informações mais detalhadas e explicar seu comentário? 

Atenciosamente, 

Equipe Internacional do Microsoft DOCS

**Comment by V-vafune** [comment]
Olá, @MuriloPetruci , 

Estamos acompanhando nosso comentário anterior. Precisamos de mais informações para podermos endereçar seus comentários. Você poderia fornecer informações mais detalhadas e explicar seu comentário? 

Atenciosamente, 

Equipe Internacional do Microsoft DOCS

**Comment by V-vafune** [comment]
Olá, @MuriloPetruci , 

Obrigado novamente por seu comentário. 

Infelizmente, ainda não temos as informações necessárias e não conseguimos processar seu comentário. Estamos fechando este problema do GitHub no momento, mas pedimos que você envie mais comentários no futuro. 

Atenciosamente, 

Equipe Internacional do Microsoft DOCS
