### ISSUE TITLE
Sobreposição de grupos

### ISSUE THREAD

**Issue by gollima** [MicrosoftDocs/azure-docs.pt-br#601]
Pode adicionar como a ferramenta se comporta quando temos sobreposição de grupos... se faz sentido criar grupos de aplicações para aplica-lo em vários lugares.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 8d5df7a3-8abc-026a-7bee-2861ba4a2e38
* Version Independent ID: 9c91b1ee-7874-a992-4e52-c621e914da08
* Content: [Controles de aplicativo adaptáveis na Central de Segurança do Azure](https://docs.microsoft.com/pt-br/azure/security-center/security-center-adaptive-application)
* Content Source: [articles/security-center/security-center-adaptive-application.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/security-center/security-center-adaptive-application.md)
* Service: **security-center**
* GitHub Login: @memildin
* Microsoft Alias: **memildin**

**Comment by srvbpigh** [comment]
Hello, @gollima
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Olá, @gollima 

Apreciamos muito a sua contribuição. Ainda assim, esses comentários se referem a produtos. Registre sua sugestão usando o botão "Fornecer comentários sobre produtos" na parte inferior da página do DOCS.

Se você tiver qualquer comentário relacionado a documentação, sinta-se livre para registrá-lo por este canal.

Verdadeiramente apreciamos sua contribuição para os nossos artigos.

Equipe internacional do Microsoft DOCS
