### ISSUE TITLE
pip install azure-storage command is deprecated

### ISSUE THREAD

**Issue by demetrioi** [MicrosoftDocs/azure-docs.pt-br#609]
The command pip install azure-storage is deprecated 

" Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all"

[Insira comentários aqui]

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 1661ae0f-130e-8ec1-94f0-ca184223bca6
* Version Independent ID: f88ca50c-493a-d357-e67f-0bcbaf1d6745
* Content: [Início Rápido: Ler dados capturados do aplicativo Python – Hubs de Eventos do Azure](https://docs.microsoft.com/pt-br/azure/event-hubs/event-hubs-capture-python)
* Content Source: [articles/event-hubs/event-hubs-capture-python.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/event-hubs/event-hubs-capture-python.md)
* Service: **event-hubs**
* GitHub Login: @ShubhaVijayasarathy
* Microsoft Alias: **shvija**

**Comment by srvbpigh** [comment]
Hello, @demetrioi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #56503](https://github.com/MicrosoftDocs/azure-docs/issues/56503) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @demetrioi, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/56503. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
