### ISSUE TITLE
Transalate error

### ISSUE THREAD

**Issue by Perdiga** [MicrosoftDocs/azure-docs.pt-br#638]
Hi, there is an error on this page. The location should be `São Paulo` and not `São Paula` as written in the English version of this document

![image](https://user-images.githubusercontent.com/5549410/103235075-f5b49b00-491f-11eb-9ccd-215873126243.png)

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: a0acd798-2e5a-2a7e-bb14-7424576a8e38
* Version Independent ID: 841f2ce1-b101-0fbf-e33d-4e56a6244ed9
* Content: [Locais e provedores de conectividade: Azure ExpressRoute](https://docs.microsoft.com/pt-br/azure/expressroute/expressroute-locations-providers#global-commercial-azure)
* Content Source: [articles/expressroute/expressroute-locations-providers.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/expressroute/expressroute-locations-providers.md)
* Service: **expressroute**
* GitHub Login: @duongau
* Microsoft Alias: **duau**

**Comment by duongau** [comment]
@Perdiga Thank you for bringing this to our attention. I have corrected the spelling mistake and it should reflect in the next couple of hours. Have a great day ahead!

#please-close
