### ISSUE TITLE
Atualização de Informações, Templates ou Figuras

### ISSUE THREAD

**Issue by leandrobsilva** [MicrosoftDocs/azure-docs.pt-br#92]
**Informação incorreta** 

- [ ] Na caixa de diálogo Novo Projeto, selecione Visual C# > Web > Aplicativo Web ASP.NET Core.

- [ ] Verifique se o Serviço de Aplicativo do Microsoft Azure está selecionado e clique em Publicar.
 
- [ ] Encontre o rótulo HTML <div class="jumbotron"> próximo à parte superior e substitua o elemento inteiro pelo seguinte código:

**Considerações**:

Usando o VS2017 houve mudança no template. Dessa forma, o roteiro produzido torna-se incorreto para um iniciante.

**Comment by CeciAc** [comment]
Olá, @leandrobsilva 
Agradecemos seus comentários. 
Vamos analisar seus comentários e daremos um retorno para você em breve. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS

**Comment by CeciAc** [comment]
Olá, @leandrobsilva 
Por favor, forneça o URL onde você encontrou este erro.

Atenciosamente,
Equipe Internacional do Microsoft DOCS

**Comment by CeciAc** [comment]
Olá, @leandrobsilva  

Não temos informações suficientes para processar a sua pergunta assim que nós estamos fechando este problema.

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 

Equipe Internacional do Microsoft DOCS 

@SunnyDeng
