### ISSUE TITLE
Armazenamento

### ISSUE THREAD

**Issue by yurihmp** [MicrosoftDocs/azure-docs.pt-br#96]
Quando eu crio uma tabela externa do banco A no banco B, essas informações são persistidas (ou seja, existe ai um processamento/uso de disco/possível queda de performance), ou apenas referenciadas? Obrigado!

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: c1e79991-5825-bd56-e5dc-567c5eac23e1
* Version Independent ID: aa72757c-f7a8-0cc7-1eaf-488569016711
* Content: [Consulta entre bancos de dados na nuvem com esquemas diferentes](https://docs.microsoft.com/pt-br/azure/sql-database/sql-database-elastic-query-vertical-partitioning)
* Content Source: [articles/sql-database/sql-database-elastic-query-vertical-partitioning.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/sql-database/sql-database-elastic-query-vertical-partitioning.md)
* Service: **sql-database**
* GitHub Login: @MladjoA
* Microsoft Alias: **mlandzic**

**Comment by CeciAc** [comment]
Olá, @yurihmp,  

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação. 

Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS. 

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal. 

Agradecemos sua contribuição aos nossos artigos.  

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
