### ISSUE TITLE
What about Managed Disks?

### ISSUE THREAD

**Issue by cdaniel96** [MicrosoftDocs/azure-docs.pt-br#97]
Hey guys, this guide is really good when you're using traditional disks using page blobs, but is that possible to recreate this virtual machine using Managed Disks instead?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 7eed234f-9a8d-4c1b-2368-fe4c8fbe8299
* Version Independent ID: 876980d5-e42c-b070-c0a6-73ed3f2c91d1
* Content: [Alterar um conjunto de disponibilidade de VM](https://docs.microsoft.com/pt-br/azure/virtual-machines/windows/change-availability-set?toc=%2Fazure%2Fvirtual-machines%2Fwindows%2Ftoc.json#next-steps)
* Content Source: [articles/virtual-machines/windows/change-availability-set.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/virtual-machines/windows/change-availability-set.md)
* Service: **virtual-machines-windows**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by cynthn** [comment]
@cdaniel96 Thanks for the feedback! I recently re-wrote the English version to use managed disks, but I'm not sure how long it will take to get it translated and published in your locale.

**Comment by LisandroSu** [comment]
Olá, @cdaniel96  

Agradecemos seus comentários. 

Nossa equipe de engenharia analisou suas sugestões e as aceitou. Implementamos seus comentários e os publicamos nos artigos atualizados no site de documentos, nas páginas a seguir https://docs.microsoft.com/pt-br/azure/virtual-machines/windows/attach-managed-disk-portal?toc=%2fazure%2fvirtual-machines%2fwindows%2ftoc.json  

Agradecemos sua contribuição aos nossos artigos e o incentivamos a continuar fornecendo seus valiosos comentários. 

Atenciosamente, 
Equipe Internacional do Microsoft DOCS
