### ISSUE TITLE
Adicionar

### ISSUE THREAD

**Issue by leo130ms** [MicrosoftDocs/azure-docs.pt-br#99]
É possóvel adicionar VMs existentes a um devTest lab?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: c9d54f47-eab3-141c-d5a8-21d29ddc1b51
* Version Independent ID: d77ab63a-c5b7-6bdb-0ab8-5e1d651af079
* Content: [Adicionar uma VM a um laboratório no Azure DevTest Labs](https://docs.microsoft.com/pt-br/azure/lab-services/devtest-lab-add-vm)
* Content Source: [articles/lab-services/devtest-lab-add-vm.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/live/articles/lab-services/devtest-lab-add-vm.md)
* Service: **devtest-lab**
* GitHub Login: @spelluru
* Microsoft Alias: **spelluru**

**Comment by gosali** [comment]
Olá, @leo130ms ,   

Sua contribuição é muito bem-vinda. Nossa equipe só pode responder a comentários relacionados à documentação.  
 
Registre os comentários do seu produto usando o botão "Comentários sobre o produto" na parte inferior da página de DOCS.  

Se você tiver comentários relacionados à documentação, fique à vontade para registrá-los por meio deste canal.  


Agradecemos sua contribuição aos nossos artigos.   

@SunnyDeng  

Atenciosamente,  

Equipe Internacional do Microsoft DOCS
